name: finalproject
description: A new Flutter project.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  csv: ^5.0.0
  path_provider: ^2.0.11
  cupertino_icons: ^1.0.2  # Add Cupertino icons dependency
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.1
  flutter_datetime_picker: ^1.5.1
  # Add other dependencies here

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true  # Ensure material design icons are included

  assets:
    - images/  # This will include all assets in the images directory
    - Excels/
