// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBYCfnUaW5EdHd1wcQwUiY8391jGKFwY0',
    appId: '1:533500950649:web:4529919db246bda458fca8',
    messagingSenderId: '533500950649',
    projectId: 'pillpopin-dbe00',
    authDomain: 'pillpopin-dbe00.firebaseapp.com',
    storageBucket: 'pillpopin-dbe00.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHxuR9gKlVsQl44YWjbTnOhu5uvEKzTUU',
    appId: '1:533500950649:android:691ca502ab7543f758fca8',
    messagingSenderId: '533500950649',
    projectId: 'pillpopin-dbe00',
    storageBucket: 'pillpopin-dbe00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9pVdlxDwHUc82tnnvaLWIso99zOA6vH8',
    appId: '1:533500950649:ios:2c3f82bcf087408558fca8',
    messagingSenderId: '533500950649',
    projectId: 'pillpopin-dbe00',
    storageBucket: 'pillpopin-dbe00.appspot.com',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9pVdlxDwHUc82tnnvaLWIso99zOA6vH8',
    appId: '1:533500950649:ios:2c3f82bcf087408558fca8',
    messagingSenderId: '533500950649',
    projectId: 'pillpopin-dbe00',
    storageBucket: 'pillpopin-dbe00.appspot.com',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBYCfnUaW5EdHd1wcQwUiY8391jGKFwY0',
    appId: '1:533500950649:web:c435480509e4240e58fca8',
    messagingSenderId: '533500950649',
    projectId: 'pillpopin-dbe00',
    authDomain: 'pillpopin-dbe00.firebaseapp.com',
    storageBucket: 'pillpopin-dbe00.appspot.com',
  );
}
